micronaut:
  application:
    name: demo
  server:
    port: 8002

thing:
  host: 127.0.0.1:8002

db:
  database: THING
  host: 127.0.0.1:3308
  user: root
  pass: thing-root

jpa:
  default:
    reactive: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        connection:
          url: jdbc:mariadb://${db.host}/${db.database}
          username: ${db.user}
          password: ${db.pass}
