micronaut:
  application:
    name: demo
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        connection:
          db-type: mariadb
    reactive: true
vertx:
  mysql:
    client:
      port: 3306
      host: the-host
      database: the-db
      user: user
      password: password
      maxSize: 5
netty:
  default:
    allocator:
      max-order: 3
